spec:aria:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'index.html'

spec:accname:
  any:
    - changed-files:
        - any-glob-to-any-file: 'accname/**'

spec:core-aam:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'core-aam/**'

spec:dpub-aam:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'dpub-aam/**'

spec:dpub-aria:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'dpub-aria/**'

spec:graphics-aam:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'graphics-aam/**'

spec:graphics-aria:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'graphics-aria/**'

spec:html-aam:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'html-aam/**'

spec:svg-aam:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'svg-aam/**'

spec:mathml-aam:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'mathml-aam/**'
spec:pdf-aam:
  - any:
    - changed-files:
        - any-glob-to-any-file: 'pdf-aam/**'
